### ISSUE TITLE
Uncaught ReferenceError: areCommented is not defined

### ISSUE THREAD

**Issue by taner-yilmaz** [rGalrito/comment-block#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.189.0
**System**: Microsoft Windows 8.1 Single Language
**Thrown From**: [comment-block](https://github.com/rGalrito/comment-block) package, v0.1.7
### Stack Trace

Uncaught ReferenceError: areCommented is not defined

```
At C:\Users\Taner\.atom\packages\comment-block\lib\comment-block.js:32

ReferenceError: areCommented is not defined
  at atom-workspace.module.exports.convert (C:\Users\Taner\.atom\packages\comment-block\lib\comment-block.js:32:11)
  at atom-workspace.handler (C:\Users\Taner\AppData\Local\atom\app-0.189.0\resources\app\src\space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (C:\Users\Taner\AppData\Local\atom\app-0.189.0\resources\app\node_modules\space-pen\vendor\jquery.js:4681:9)
  at atom-workspace.elemData.handle (C:\Users\Taner\AppData\Local\atom\app-0.189.0\resources\app\node_modules\space-pen\vendor\jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Taner\AppData\Local\atom\app-0.189.0\resources\app\src\command-registry.js:242:29)
  at C:\Users\Taner\AppData\Local\atom\app-0.189.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Taner\AppData\Local\atom\app-0.189.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:552:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Taner\AppData\Local\atom\app-0.189.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:392:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Taner\AppData\Local\atom\app-0.189.0\resources\app\src\window-event-handler.js:180:20)

```
### Commands

```
  2x -3:31.4 core:move-down (atom-text-editor.editor.mini)
     -3:00.7 editor:newline (atom-text-editor.editor)
  3x -2:59.2 core:backspace (atom-text-editor.editor)
     -2:58.1 snippets:next-tab-stop (atom-text-editor.editor)
     -2:58.1 snippets:expand (atom-text-editor.editor)
     -2:58.0 editor:indent (atom-text-editor.editor)
     -2:52.1 atom-alignment:alignMultiple (atom-text-editor.editor)
     -2:49.0 core:delete (atom-text-editor.editor)
     -2:48.0 core:save (atom-text-editor.editor)
     -2:00.6 core:confirm (atom-text-editor.editor.mini)
     -1:54.3 core:backspace (atom-text-editor.editor.mini)
     -1:36.7 core:confirm (atom-text-editor.editor.mini)
  2x -0:33.5 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:29.6 core:undo (atom-text-editor.editor.is-focused)
     -0:26.7 core:save (atom-text-editor.editor.is-focused)
     -0:04.0 comment-block:convert (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-alignment, v0.12.0
comment-block, v0.1.7

# Dev
No dev packages
```

**Comment by rGalrito** [comment]
Hey! Thanks for your report! :)

I've done some small changes, so that this error is not thrown anymore. I will continue development to have multiple lines feature when I have some more free time. 

Despite that, I'd be happy to see some pull requests.

Rafael.
